# Stage 1: Build
FROM node:18 AS build

WORKDIR /usr/src/app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy all source files
COPY . .

# Install global dependencies
RUN yarn global add prisma prisma-dbml-generator

# Generate Prisma client
RUN yarn prisma generate

# Build the application
RUN yarn build

# Stage 2: Development (Optional)
FROM node:18 AS dev
ENV NODE_ENV=development
WORKDIR /usr/src/app

# Copy necessary files from the build stage
COPY --from=build /usr/src/app/package.json ./
COPY --from=build /usr/src/app/yarn.lock ./
COPY --from=build /usr/src/app/prisma ./prisma
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/build ./build

# Install all dependencies (including dev dependencies)
RUN yarn install

# Expose the necessary port
EXPOSE 4006

# Start the application in development mode
CMD [ "yarn", "dev" ]

# Stage 3: Production
FROM node:18-alpine AS production

WORKDIR /usr/src/app

# Copy necessary files from the build stage
COPY --from=build /usr/src/app/package.json ./
COPY --from=build /usr/src/app/yarn.lock ./
COPY --from=build /usr/src/app/prisma ./prisma
COPY --from=build /usr/src/app/build ./build

# Install only production dependencies
RUN yarn install --production

# Expose the necessary port
EXPOSE 4006

# Start the application
CMD [ "yarn", "start" ]
