version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: "fms-prod-app"
    restart: on-failure
    ports:
      - "2026:2026"
    env_file:
      - .env
    environment:
      HOST: app:2026
      PORT: 2026
      DATABASE_URL: postgres://POSTGRES_USER:POSTGRES_PASSWORD@postgres_db:5432/POSTGRES_DB
      NODE_ENV: production
      JWT_SECRET: adds!@#sdwe
      JWT_ACCESS_EXPIRATION_MINUTES: 5675
    depends_on:
      - postgres_db
    command: >
      sh -c "
        npx prisma generate && 
        npx prisma migrate deploy && 
        yarn db:seed && 
        yarn start
      "
    volumes:
      - .:/usr/src/app
    networks:
      - fms-prod-networks

  postgres_db:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_DB=POSTGRES_DB
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - fms-prod-networks

volumes:
  postgres_data:

networks:
  fms-prod-networks:
    driver: bridge